const UsersActionTypes = {
    ////fetch
    FETCH_USERS_START: "FETCH_USERS_START",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
    ///delete
    DELETE_USER_START: "DELETE_USER_START",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
    ////add
    ADD_USER_START: "ADD_USER_START",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_FAILURE: "ADD_USER_FAILURE",
    //update
    UPDATE_USER_START: "UPDATE_USER_START",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
};

    export default UsersActionTypes;
